version: '3.7'
services:   
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: patryk
            POSTGRES_PASSWORD: password

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
